export const defaultValues = {
    nombre: '',
    apellido: '',
    tipo_identificacion: '',
    identificacion: '',
    fecha_nacimiento: '',
    sexo: '',
    identidad_genero: '',
    identidad_sexual: '',
    estrato: '',
    ocupacion: '',
    residente: '',
    direccion: '',
    procedente: '',
    regimen: '',
    celular: '',
    correo: '',
    municipio: '',
    departamento: '',
}
